### ISSUE TITLE
Caption data is missing in the repo

### ISSUE THREAD

**Issue by moyutianque** [expectorlin/NavCoT#2]
Hi thanks for the work. args.candidate_cap_dir are required in the code, but the data are not released

**Comment by ShunchiZhang** [comment]
Same problem here. Hi @expectorlin, would you kindly release the candidate caption data? Thank you so much :)

<details open>
<summary>Error log (r2r testing)</summary>

```python
Traceback (most recent call last):
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/main.py", line 315, in <module>
    main()
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/main.py", line 311, in main
    valid(args, train_env, val_envs, rank=rank)
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/main.py", line 272, in valid
    agent.test(use_dropout=False, feedback='argmax', iters=iters)
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/agent_cmt.py", line 1113, in test
    super().test(iters=iters, rollout_function=self.rollout_llm)
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/agent_base.py", line 42, in test
    for traj in rollout_function(**kwargs):
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/agent_cmt.py", line 1007, in rollout_llm
    obs = self.env.reset()
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/env.py", line 373, in reset
    return self._get_obs(t=0)
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/env.py", line 337, in _get_obs
    candidate = self.make_candidate(feature, state.scanId, state.location.viewpointId, state.viewIndex, probs)
  File "/workspace/expectorlin/NavCoT/finetune_src/r2r/env.py", line 222, in make_candidate
    with open(candidate_caption_dir) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/captions/QUCTc6BB5sX/471a6f3beedb4cc7a71edc7fc1c5275b/QUCTc6BB5sX_471a6f3beedb4cc7a71edc7fc1c5275b.json'
```

</details>

**Comment by expectorlin** [comment]
Thanks for your interest and kind reminder! We have uploaded the caption data to the dropbox. Please see the readme file for details!
